# Example configuration for Knowledge Base Engine

[database]
db_host = "localhost"
db_port = 5432
db_name = "your_db_name"
db_user = "your_db_user"
db_password = "your_db_password"

[ollama]
ollama_url = "http://localhost:11434"
model = "your_model_name"
